FROM python:3-slim

COPY requirements.prod.txt /requirements.txt

RUN pip install -r /requirements.txt

WORKDIR /usr/src/app/drf_sp_hub

EXPOSE 8000
CMD [ "gunicorn", "sp_hub.wsgi", "-b", "0.0.0.0:8000" ]
